name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bezysoftware
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.Release
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            APP_VERSION=${{ github.event.release.tag_name }}
          push: true
          tags: bezysoftware/autosats:${{ github.event.release.tag_name }},bezysoftware/autosats:latest
          platforms: linux/arm64,linux/amd64